// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mute.proto

package protofiles

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Mute struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Sender               string   `protobuf:"bytes,2,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Target               string   `protobuf:"bytes,3,opt,name=Target,proto3" json:"Target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mute) Reset()         { *m = Mute{} }
func (m *Mute) String() string { return proto.CompactTextString(m) }
func (*Mute) ProtoMessage()    {}
func (*Mute) Descriptor() ([]byte, []int) {
	return fileDescriptor_c074e602f8a8801a, []int{0}
}

func (m *Mute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mute.Unmarshal(m, b)
}
func (m *Mute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mute.Marshal(b, m, deterministic)
}
func (m *Mute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mute.Merge(m, src)
}
func (m *Mute) XXX_Size() int {
	return xxx_messageInfo_Mute.Size(m)
}
func (m *Mute) XXX_DiscardUnknown() {
	xxx_messageInfo_Mute.DiscardUnknown(m)
}

var xxx_messageInfo_Mute proto.InternalMessageInfo

func (m *Mute) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Mute) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Mute) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func init() {
	proto.RegisterType((*Mute)(nil), "protofiles.Mute")
}

func init() { proto.RegisterFile("mute.proto", fileDescriptor_c074e602f8a8801a) }

var fileDescriptor_c074e602f8a8801a = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x2d, 0x2d, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x53, 0x69, 0x99, 0x39, 0xa9, 0xc5, 0x4a,
	0x5e, 0x5c, 0x2c, 0xbe, 0xa5, 0x25, 0xa9, 0x42, 0x42, 0x5c, 0x2c, 0x21, 0x95, 0x05, 0xa9, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x60, 0xb6, 0x90, 0x18, 0x17, 0x5b, 0x70, 0x6a, 0x5e, 0x4a,
	0x6a, 0x91, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x94, 0x07, 0x12, 0x0f, 0x49, 0x2c, 0x4a,
	0x4f, 0x2d, 0x91, 0x60, 0x86, 0x88, 0x43, 0x78, 0x49, 0x6c, 0x60, 0x73, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x4d, 0x3c, 0x70, 0xf0, 0x6c, 0x00, 0x00, 0x00,
}
