// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session.proto

package protofiles

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Session struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Role                 uint32   `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	Confirmed            bool     `protobuf:"varint,5,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Active               bool     `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	Subscription         uint64   `protobuf:"varint,7,opt,name=subscription,proto3" json:"subscription,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{0}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Session) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Session) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Session) GetRole() uint32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *Session) GetConfirmed() bool {
	if m != nil {
		return m.Confirmed
	}
	return false
}

func (m *Session) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Session) GetSubscription() uint64 {
	if m != nil {
		return m.Subscription
	}
	return 0
}

func init() {
	proto.RegisterType((*Session)(nil), "protofiles.Session")
}

func init() { proto.RegisterFile("session.proto", fileDescriptor_3a6be1b361fa6f14) }

var fileDescriptor_3a6be1b361fa6f14 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xcb, 0xca, 0xc2, 0x30,
	0x10, 0x46, 0x49, 0xff, 0x5e, 0x87, 0xbf, 0x2e, 0x06, 0x91, 0x20, 0x2e, 0x42, 0x57, 0x59, 0xb9,
	0xf1, 0x4d, 0xe2, 0x13, 0xf4, 0x32, 0x85, 0x81, 0x36, 0x29, 0x49, 0xeb, 0xbb, 0xf9, 0x76, 0x42,
	0x2a, 0x8a, 0xab, 0x99, 0x73, 0xce, 0xea, 0x83, 0x3a, 0x50, 0x08, 0xec, 0xec, 0x75, 0xf1, 0x6e,
	0x75, 0x08, 0xf1, 0x8c, 0x3c, 0x51, 0x68, 0x9e, 0x02, 0x8a, 0xfb, 0x5e, 0xf1, 0x00, 0x09, 0x0f,
	0x52, 0x28, 0xa1, 0x2b, 0x93, 0xf0, 0x80, 0x47, 0xc8, 0x68, 0x6e, 0x79, 0x92, 0x49, 0x54, 0x3b,
	0xe0, 0x19, 0xca, 0x2d, 0x90, 0xb7, 0xed, 0x4c, 0xf2, 0x2f, 0x86, 0x0f, 0x23, 0x42, 0xea, 0xdd,
	0x44, 0x32, 0x55, 0x42, 0xd7, 0x26, 0xfe, 0x78, 0x81, 0xaa, 0x77, 0x76, 0x64, 0x3f, 0xd3, 0x20,
	0x33, 0x25, 0x74, 0x69, 0xbe, 0x02, 0x4f, 0x90, 0xb7, 0xfd, 0xca, 0x0f, 0x92, 0x79, 0x4c, 0x6f,
	0xc2, 0x06, 0xfe, 0xc3, 0xd6, 0x85, 0xde, 0xf3, 0xb2, 0xb2, 0xb3, 0xb2, 0x50, 0x42, 0xa7, 0xe6,
	0xc7, 0x75, 0x79, 0xdc, 0x71, 0x7b, 0x05, 0x00, 0x00, 0xff, 0xff, 0xf6, 0xbe, 0xe8, 0x06, 0xdf,
	0x00, 0x00, 0x00,
}
